package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbApplicationChatRecord;

/**
 * Generated by java-db.
 */
public class MaxKbApplicationChatRecord extends BaseMaxKbApplicationChatRecord<MaxKbApplicationChatRecord> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbApplicationChatRecord dao = new MaxKbApplicationChatRecord().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_application_chat_record";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String voteStatus
  // private java.lang.String problemText
  // private java.lang.String answerText
  // private java.lang.Integer messageTokens
  // private java.lang.Integer answerTokens
  // private java.lang.Integer _const
  // private java.lang.String details
  // private java.lang.Long[] improveParagraphIdList
  // private java.lang.Double runTime
  // private java.lang.Integer index
  // private java.lang.Long chatId
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

