package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbFile;

/**
 * Generated by java-db.
 */
public class MaxKbFile extends BaseMaxKbFile<MaxKbFile> {
  private static final long serialVersionUID = 1L;
  public static final MaxKbFile dao = new MaxKbFile().dao();
  /**
   * 
   */
  public static final String tableName = "max_kb_file";
  public static final String primaryKey = "id";

  // private java.lang.Long id
  // private java.lang.String md5
  // private java.lang.String filename
  // private java.lang.Long fileSize
  // private java.lang.String userId
  // private java.lang.String platform
  // private java.lang.String regionName
  // private java.lang.String bucketName
  // private java.lang.String fileId
  // private java.lang.String targetName
  // private java.lang.Object tags
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId
  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}
