package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbProblem;

/**
 * Generated by java-db.
 */
public class MaxKbProblem extends BaseMaxKbProblem<MaxKbProblem> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbProblem dao = new MaxKbProblem().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_problem";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String content
  // private java.lang.Integer hitNum
  // private java.lang.Long datasetId
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

