package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbApplicationTempSetting;

/**
 * Generated by java-db.
 */
public class MaxKbApplicationTempSetting extends BaseMaxKbApplicationTempSetting<MaxKbApplicationTempSetting> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbApplicationTempSetting dao = new MaxKbApplicationTempSetting().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_application_temp_setting";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String setting

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

