package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbParagraph;

/**
 * Generated by java-db.
 */
public class MaxKbParagraph extends BaseMaxKbParagraph<MaxKbParagraph> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbParagraph dao = new MaxKbParagraph().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_paragraph";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.Long sourceId
  // private java.lang.String sourceType
  // private java.lang.String title
  // private java.lang.String content
  // private java.lang.String md5
  // private java.lang.String status
  // private java.lang.Integer hitNum
  // private java.lang.Boolean isActive
  // private java.lang.Long datasetId
  // private java.lang.Long documentId
  // private java.lang.String embedding
  // private java.lang.String meta
  // private java.lang.String searchVector
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

