package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbDataset;

/**
 * Generated by java-db.
 */
public class MaxKbDataset extends BaseMaxKbDataset<MaxKbDataset> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbDataset dao = new MaxKbDataset().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_dataset";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String name
  // private java.lang.String desc
  // private java.lang.String type
  // private java.lang.Long embeddingModeId
  // private java.lang.String meta
  // private java.lang.Long userId
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

