package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbProblemParagraphMapping;

/**
 * Generated by java-db.
 */
public class MaxKbProblemParagraphMapping extends BaseMaxKbProblemParagraphMapping<MaxKbProblemParagraphMapping> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbProblemParagraphMapping dao = new MaxKbProblemParagraphMapping().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_problem_paragraph_mapping";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.Long datasetId
  // private java.lang.Long documentId
  // private java.lang.Long paragraphId
  // private java.lang.Long problemId
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

