package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbDocument;

/**
 * Generated by java-db.
 */
public class MaxKbDocument extends BaseMaxKbDocument<MaxKbDocument> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbDocument dao = new MaxKbDocument().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_document";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.Long fileId
  // private java.lang.Long userId
  // private java.lang.String title
  // private java.lang.String name
  // private java.lang.Integer charLength
  // private java.lang.String status
  // private java.lang.Boolean isActive
  // private java.lang.String type
  // private java.lang.String meta
  // private java.lang.Long datasetId
  // private java.lang.String hitHandlingMethod
  // private java.lang.Double directlyReturnSimilarity
  // private java.lang.Integer paragraphCount
  // private java.lang.Object files
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

