package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbDocumentMarkdownPageCache;

/**
 * Generated by java-db.
 */
public class MaxKbDocumentMarkdownPageCache extends BaseMaxKbDocumentMarkdownPageCache<MaxKbDocumentMarkdownPageCache> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbDocumentMarkdownPageCache dao = new MaxKbDocumentMarkdownPageCache().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_document_markdown_page_cache";
  public static final String primaryKey = "id";
  // private java.lang.String id
  // private java.lang.String target
  // private java.lang.String content
  // private java.lang.Long elapsed
  // private java.lang.String model
  // private java.lang.String systemFingerprint
  // private java.lang.Integer completionTokens
  // private java.lang.Integer promptTokens
  // private java.lang.Integer totalTokens

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

