package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbApplicationChat;

/**
 * Generated by java-db.
 */
public class MaxKbApplicationChat extends BaseMaxKbApplicationChat<MaxKbApplicationChat> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbApplicationChat dao = new MaxKbApplicationChat().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_application_chat";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String _abstract
  // private java.lang.Long applicationId
  // private java.lang.Long clientId
  // private java.lang.Integer chatType
  // private java.lang.Boolean isDeleted
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

