package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbModel;

/**
 * Generated by java-db.
 */
public class MaxKbModel extends BaseMaxKbModel<MaxKbModel> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbModel dao = new MaxKbModel().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_model";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String name
  // private java.lang.String modelType
  // private java.lang.String modelName
  // private java.lang.String provider
  // private java.lang.String credential
  // private java.lang.Long userId
  // private java.lang.String meta
  // private java.lang.String status
  // private java.lang.String permissionType
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

