package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbEmbeddingCache;

/**
 * Generated by java-db.
 */
public class MaxKbEmbeddingCache extends BaseMaxKbEmbeddingCache<MaxKbEmbeddingCache> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbEmbeddingCache dao = new MaxKbEmbeddingCache().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_embedding_cache";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String t
  // private java.lang.String m
  // private java.lang.String v
  // private java.lang.String md5

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

