package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbApplicationDatasetMapping;

/**
 * Generated by java-db.
 */
public class MaxKbApplicationDatasetMapping extends BaseMaxKbApplicationDatasetMapping<MaxKbApplicationDatasetMapping> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbApplicationDatasetMapping dao = new MaxKbApplicationDatasetMapping().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_application_dataset_mapping";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.Long applicationId
  // private java.lang.Long datasetId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

