package com.litongjava.maxkb.model;

import com.litongjava.maxkb.model.base.BaseMaxKbUser;

/**
 * Generated by java-db.
 */
public class MaxKbUser extends BaseMaxKbUser<MaxKbUser> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbUser dao = new MaxKbUser().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_user";
  public static final String primaryKey = "id";
  // private java.lang.Long id
  // private java.lang.String email
  // private java.lang.String phone
  // private java.lang.String nickName
  // private java.lang.String username
  // private java.lang.String password
  // private java.lang.String role
  // private java.lang.Boolean isActive
  // private java.lang.String source
  // private java.lang.String remark
  // private java.lang.String creator
  // private java.util.Date createTime
  // private java.lang.String updater
  // private java.util.Date updateTime
  // private java.lang.Integer deleted
  // private java.lang.Long tenantId

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

