app.env=dev
server.port=10060
#tio.http.request.printUrl=true
server.http.controller.printMapping=true
server.http.request.printReport=true
http.multipart.max-request-size=110100480
http.multipart.max-file-size=104857600
server.resources.static-locations=pages
server.http.response.cors.enable=true
app.token.timeout=604800
app.name=java-maxkb
