package nexus.io.mosskb.model;

import nexus.io.db.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("moss_kb_application", "id", MossKbApplication.class);
		arp.addMapping("moss_kb_application_access_token", "application_id", MossKbApplicationAccessToken.class);
		arp.addMapping("moss_kb_application_chat", "id", MossKbApplicationChat.class);
		arp.addMapping("moss_kb_application_chat_record", "id", MossKbApplicationChatRecord.class);
		arp.addMapping("moss_kb_application_dataset_mapping", "id", MossKbApplicationDatasetMapping.class);
		arp.addMapping("moss_kb_application_public_access_client", "id", MossKbApplicationPublicAccessClient.class);
		arp.addMapping("moss_kb_application_temp_setting", "id", MossKbApplicationTempSetting.class);
		arp.addMapping("moss_kb_dataset", "id", MossKbDataset.class);
		arp.addMapping("moss_kb_document", "id", MossKbDocument.class);
		arp.addMapping("moss_kb_document_markdown_cache", "id", MossKbDocumentMarkdownCache.class);
		arp.addMapping("moss_kb_document_markdown_page_cache", "id", MossKbDocumentMarkdownPageCache.class);
		arp.addMapping("moss_kb_embedding_cache", "id", MossKbEmbeddingCache.class);
		arp.addMapping("moss_kb_file", "id", MossKbFile.class);
		arp.addMapping("moss_kb_model", "id", MossKbModel.class);
		arp.addMapping("moss_kb_paragraph", "id", MossKbParagraph.class);
		arp.addMapping("moss_kb_paragraph_summary_cache", "id", MossKbParagraphSummaryCache.class);
		arp.addMapping("moss_kb_problem", "id", MossKbProblem.class);
		arp.addMapping("moss_kb_problem_paragraph_mapping", "id", MossKbProblemParagraphMapping.class);
		arp.addMapping("moss_kb_sentence", "id", MossKbSentence.class);
		arp.addMapping("moss_kb_task", "id", MossKbTask.class);
		arp.addMapping("moss_kb_user", "id", MossKbUser.class);
		arp.addMapping("moss_kb_user_token", "id", MossKbUserToken.class);
	}
}


