package nexus.io.mosskb.model;

import nexus.io.mosskb.model.base.BaseMossKbParagraphSummaryCache;

/**
 * Generated by java-db.
 */
public class MossKbParagraphSummaryCache extends BaseMossKbParagraphSummaryCache<MossKbParagraphSummaryCache> {
  private static final long serialVersionUID = 1L;
	public static final MossKbParagraphSummaryCache dao = new MossKbParagraphSummaryCache().dao();
	/**
	 * 
	 */
  public static final String tableName = "moss_kb_paragraph_summary_cache";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String md5 = "md5";
  //java.lang.String 
  public static final String src = "src";
  //java.lang.String 
  public static final String content = "content";
  //java.lang.Long 
  public static final String elapsed = "elapsed";
  //java.lang.String 
  public static final String model = "model";
  //java.lang.String 
  public static final String systemFingerprint = "system_fingerprint";
  //java.lang.Integer 
  public static final String completionTokens = "completion_tokens";
  //java.lang.Integer 
  public static final String promptTokens = "prompt_tokens";
  //java.lang.Integer 
  public static final String totalTokens = "total_tokens";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

