package nexus.io.mosskb.model;

import nexus.io.mosskb.model.base.BaseMossKbDataset;

/**
 * Generated by java-db.
 */
public class MossKbDataset extends BaseMossKbDataset<MossKbDataset> {
  private static final long serialVersionUID = 1L;
	public static final MossKbDataset dao = new MossKbDataset().dao();
	/**
	 * 
	 */
  public static final String tableName = "moss_kb_dataset";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String name = "name";
  //java.lang.String 
  public static final String desc = "desc";
  //java.lang.String 
  public static final String type = "type";
  //java.lang.Long 
  public static final String embeddingModeId = "embedding_mode_id";
  //java.lang.Long 
  public static final String llmModeId = "llm_mode_id";
  //java.lang.String 
  public static final String meta = "meta";
  //java.lang.Long 
  public static final String userId = "user_id";
  //java.lang.String 
  public static final String remark = "remark";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

