package nexus.io.mosskb.model;

import nexus.io.mosskb.model.base.BaseMossKbApplicationAccessToken;

/**
 * Generated by java-db.
 */
public class MossKbApplicationAccessToken extends BaseMossKbApplicationAccessToken<MossKbApplicationAccessToken> {
  private static final long serialVersionUID = 1L;
	public static final MossKbApplicationAccessToken dao = new MossKbApplicationAccessToken().dao();
	/**
	 * 
	 */
  public static final String tableName = "moss_kb_application_access_token";
  public static final String primaryKey = "application_id";
  //java.lang.Long 
  public static final String applicationId = "application_id";
  //java.lang.Long 
  public static final String accessToken = "access_token";
  //java.lang.Boolean 
  public static final String isActive = "is_active";
  //java.lang.Integer 
  public static final String accessNum = "access_num";
  //java.lang.Boolean 
  public static final String whiteActive = "white_active";
  //java.lang.String[] 
  public static final String whiteList = "white_list";
  //java.lang.Boolean 
  public static final String showSource = "show_source";
  //java.lang.String 
  public static final String language = "language";
  //java.lang.String 
  public static final String remark = "remark";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

