package nexus.io.mosskb.model;

import nexus.io.mosskb.model.base.BaseMossKbApplicationTempSetting;

/**
 * Generated by java-db.
 */
public class MossKbApplicationTempSetting extends BaseMossKbApplicationTempSetting<MossKbApplicationTempSetting> {
  private static final long serialVersionUID = 1L;
	public static final MossKbApplicationTempSetting dao = new MossKbApplicationTempSetting().dao();
	/**
	 * 
	 */
  public static final String tableName = "moss_kb_application_temp_setting";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String setting = "setting";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

