package nexus.io.mosskb.model;

import nexus.io.mosskb.model.base.BaseMossKbSentence;

/**
 * Generated by java-db.
 */
public class MossKbSentence extends BaseMossKbSentence<MossKbSentence> {
  private static final long serialVersionUID = 1L;
	public static final MossKbSentence dao = new MossKbSentence().dao();
	/**
	 * 
	 */
  public static final String tableName = "moss_kb_sentence";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.Integer 
  public static final String type = "type";
  //java.lang.String 
  public static final String content = "content";
  //java.lang.String 
  public static final String md5 = "md5";
  //java.lang.Integer 
  public static final String hitNum = "hit_num";
  //java.lang.Long 
  public static final String datasetId = "dataset_id";
  //java.lang.Long 
  public static final String documentId = "document_id";
  //java.lang.Long 
  public static final String paragraphId = "paragraph_id";
  //java.lang.String 
  public static final String embedding = "embedding";
  //java.lang.String 
  public static final String meta = "meta";
  //java.lang.String 
  public static final String searchVector = "search_vector";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

