package nexus.io.mosskb.model;

import nexus.io.mosskb.model.base.BaseMossKbEmbeddingCache;

/**
 * Generated by java-db.
 */
public class MossKbEmbeddingCache extends BaseMossKbEmbeddingCache<MossKbEmbeddingCache> {
  private static final long serialVersionUID = 1L;
	public static final MossKbEmbeddingCache dao = new MossKbEmbeddingCache().dao();
	/**
	 * 
	 */
  public static final String tableName = "moss_kb_embedding_cache";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String t = "t";
  //java.lang.String 
  public static final String m = "m";
  //java.lang.String 
  public static final String v = "v";
  //java.lang.String 
  public static final String md5 = "md5";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

