package nexus.io.mosskb.model;

import nexus.io.mosskb.model.base.BaseMossKbDocumentMarkdownCache;

/**
 * Generated by java-db.
 */
public class MossKbDocumentMarkdownCache extends BaseMossKbDocumentMarkdownCache<MossKbDocumentMarkdownCache> {
  private static final long serialVersionUID = 1L;
	public static final MossKbDocumentMarkdownCache dao = new MossKbDocumentMarkdownCache().dao();
	/**
	 * 
	 */
  public static final String tableName = "moss_kb_document_markdown_cache";
  public static final String primaryKey = "id";
  //java.lang.String 
  public static final String id = "id";
  //java.lang.String 
  public static final String target = "target";
  //java.lang.String 
  public static final String content = "content";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

